### ISSUE TITLE
VSCode initialization in the 4.8 release

### ISSUE THREAD

**Issue by jensjako** [OPEnSLab-OSU/Loom-V4#243]
When we update to 4.8 from 4.7 on the Arduino IDE, the version control on VS no longer works
Here is the screenshots for clarity
4.7:

<img width="412" height="448" alt="Image" src="https://github.com/user-attachments/assets/d666574f-21bb-46c8-8f2c-f5fa92de87bf" />

<img width="352" height="692" alt="Image" src="https://github.com/user-attachments/assets/aa3dff35-f410-43e9-8197-2e2b8476c075" />

4.8:

<img width="508" height="462" alt="Image" src="https://github.com/user-attachments/assets/75104c46-4fc6-49a7-917f-311db154d798" />

<img width="580" height="655" alt="Image" src="https://github.com/user-attachments/assets/be245ee6-fe49-4f94-8fa0-c5eea085beb9" />

Clicking initialize repository messes everything up and you have to remove everything, so that doesn't fix it. We tried to follow the instructions from issue #234 and I don't believe the path or package_index.json is the issue either

**Comment by ReidP-source** [comment]
# Fix

Alright so here's what I'm assuming the problem is...

You're using the **4.7 folder from the arduino15 directory as your git clone of the Loom-V4 repo**. The reason it's not working when you update it to 4.8 is because **there is no git clone of the Loom-V4 repo within that package**.


**Here's me replicating your 4.7 using the path `Users/<username>/appdata/local/arduino15/packages/loom4/hardware/samd/4.7/libraries/loom/...`**

<img width="1323" alt="Image" src="https://github.com/user-attachments/assets/87ab51c5-ee72-4390-a139-33de0bc36143" />


# How I fixed it

I had to copy a **.git** from a git clone, then paste that into the **4.8 package**. There was some other git configuration required to ensure you have all branches available and to ensure the repo was placed correctly inside the Loom library. 

I've updated the **loom4.zip** on the **4.8.0 release**, but to get that onto the ArduinoIDE release it needs to go through the deployment workflow. I'm not familiar with the deployment workflow, so I'm leaving you with a temporary manual fix.

@SeamusTappert can re-release 4.8.0 or add the .git to 4.8.1 so you can use it as a git clone in the future.

# Temporary Fix (Manual Steps)

**Warning:** It's a bit of a pain...

1. **Download and extract** the `loom4.zip` from the **4.8.0 release** into:
> C:Users/<username>/appdata/local/arduino15/packages/loom4/hardware/samd/4.8/
2. Open the newly extracted **loom4** directory inside the `4.8` folder.
3. Press **CTRL+A** then **CTRL+X** to cut the entire contents.
4. Go back up one directory (to the main `4.8` folder).
5. Press **CTRL+V** to paste the files, accepting any overwrite prompts.
6. Delete the now-empty `loom4` folder.
7. You can now use the updated 4.8 directory as your git clone.

<img width="763" alt="Image" src="https://github.com/user-attachments/assets/67c6889d-1d97-49c2-b09e-9a072e23cf79" />

## To ensure you're on the proper folder on VSCode navigate to the path

> C:Users/<username>/appdata/local/arduino15/packages/loom4/hardware/samd/4.8/libraries/loom/

**Comment by jensjako** [comment]
When we tried to go through your steps, I had to begin by updating to 4.8 on the Arduino IDE, we got this error message

<img width="1918" height="945" alt="Image" src="https://github.com/user-attachments/assets/f574c438-dcf2-4354-99d7-d44e9e13cc64" />

Failed to install platform: 'Loom SAMD Boards V4:4.8'. 13 INTERNAL: Cannot install platform: installing platform loom4:samd@4.8: testing local archive integrity: testing archive checksum: archive hash differs from hash in index

We think this has to do with the recent change to auxiliray/package_loom4_index.json

<img width="1170" height="823" alt="Image" src="https://github.com/user-attachments/assets/9fa8a05f-0c4a-4aa4-a62e-1e658f9f2ac7" />

**Comment by ReidP-source** [comment]
@jensjako Do you have VScode opened while trying to install the update? I do not have any issues installing the 4.8 board-profile except if VScode is open with the library.

**Comment by jensjako** [comment]
@ReidP-source We didn't have VSCode open, me and 3 other people all tried to update and it gave us all the same error. Did it just now work for you?

**Comment by ReidP-source** [comment]
@jensjako You're true, the first time I tried it ~13 minutes ago it worked. When I tried again to go from 4.7 - 4.8 it didn't I'll update the checksum/size using the release and someone will need to review it.

**Comment by ReidP-source** [comment]
@jensjako attached you to the PR as a reviewer https://github.com/OPEnSLab-OSU/Loom-V4/pull/244/

**Comment by ReidP-source** [comment]
Sorry for the trouble, I assumed it wasn't going to update on Arduino without a deployment so I put off updating the index. Seems I was wrong, hopefully its fixed now.

**Comment by jensjako** [comment]
@ReidP-source I approved the changes, but its still not working, someone else should try just to make sure its not me

**Comment by ReidP-source** [comment]
@jensjako I also need to change the zip checksum and size.

**Comment by jensjako** [comment]
@ReidP-source Oooh okay I get it, Ill try it later after it updates?

**Comment by ReidP-source** [comment]
@jensjako I got it fixed. 

<img width="1595" height="1027" alt="Image" src="https://github.com/user-attachments/assets/f916662a-7c3d-4df1-b6d8-bd5001e6bfea" />****

<img width="1760" height="947" alt="Image" src="https://github.com/user-attachments/assets/489d2126-f488-4304-afac-314e578cc397" />

## To fix it

I had to delete the **`package_loom4_index.json`** in the **`Arduino15`** folder. When you're trying to install the new file it's using the old cached index.json which has the wrong checksum. To get it to pull the new one you have to delete the old one otherwise it's defaulting to the one that it already has. 

You could also probably just copy/paste the checksum and size into that index.json to bypass deleting it but I didn't test it that way. 

_Note: I also removed the loom4 package in **`staging`** and **`packages`** from what I understand that's not necessary but if it's not working then might as well remove those too._

<img width="1070" height="525" alt="Image" src="https://github.com/user-attachments/assets/a1a80404-082a-4b92-9a39-1b946bb73bab" />

**Comment by ReidP-source** [comment]
Great! Let me know if there's any other issues. I've also updated the board profile doc for future use. It should go over all the issues we had here and more.
